Repository jenkinsci/file-parameters-plugin, pull requests merged in 2021-01, with the labels that each got.

#7 add junit test for stash file parameter
  .github/dependabot.yml
  .github/workflows/release-drafter.yml
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/file_parameters/Base64FileParameterDefinition.java
  src/main/java/io/jenkins/plugins/file_parameters/FileParameterWrapper.java
  src/main/java/io/jenkins/plugins/file_parameters/StashedFileParameterDefinition.java
  src/main/resources/io/jenkins/plugins/file_parameters/Base64FileParameterDefinition/help.html
  src/main/resources/io/jenkins/plugins/file_parameters/FileParameterWrapper/config.jelly
  src/main/resources/io/jenkins/plugins/file_parameters/FileParameterWrapper/help-allowNoFile.html
  src/main/resources/io/jenkins/plugins/file_parameters/FileParameterWrapper/help.html
  src/main/resources/io/jenkins/plugins/file_parameters/StashedFileParameterDefinition/help.html
  src/test/java/io/jenkins/plugins/file_parameters/FileParameterWrapperTest.java
Labels: enhancement

#8 Make FileParameterWrapper work with StashedFileParameterValue
  README.md
  src/main/java/io/jenkins/plugins/file_parameters/AbstractFileParameterValue.java
  src/main/java/io/jenkins/plugins/file_parameters/Base64FileParameterValue.java
  src/main/java/io/jenkins/plugins/file_parameters/FileParameterWrapper.java
  src/main/java/io/jenkins/plugins/file_parameters/StashedFileParameterValue.java
  src/test/java/io/jenkins/plugins/file_parameters/FileParameterWrapperTest.java
Labels: bug

#9 Various text edits for docs
  README.md
  src/main/resources/index.jelly
  src/main/resources/io/jenkins/plugins/file_parameters/Base64FileParameterDefinition/help.html
  src/main/resources/io/jenkins/plugins/file_parameters/FileParameterWrapper/help-allowNoFile.html
  src/main/resources/io/jenkins/plugins/file_parameters/FileParameterWrapper/help.html
  src/main/resources/io/jenkins/plugins/file_parameters/StashedFileParameterDefinition/help.html
Labels: documentation

#10 Use a simplified constructor for prettier Declarative syntax
  README.md
  src/main/java/io/jenkins/plugins/file_parameters/AbstractFileParameterDefinition.java
  src/main/java/io/jenkins/plugins/file_parameters/Base64FileParameterDefinition.java
  src/main/java/io/jenkins/plugins/file_parameters/StashedFileParameterDefinition.java
  src/main/resources/io/jenkins/plugins/file_parameters/Base64FileParameterDefinition/help.html
  src/main/resources/io/jenkins/plugins/file_parameters/FileParameterWrapper/help.html
  src/main/resources/io/jenkins/plugins/file_parameters/StashedFileParameterDefinition/help.html
  src/test/java/io/jenkins/plugins/file_parameters/AbstractFileParameterDefinitionTest.java
  src/test/java/io/jenkins/plugins/file_parameters/FileParameterWrapperTest.java
Labels: enhancement

#11 Tested REST submission
  README.md
  src/test/java/io/jenkins/plugins/file_parameters/AbstractFileParameterDefinitionTest.java
Labels: tests

#12 Handle empty description better in snippet generator
  src/main/java/io/jenkins/plugins/file_parameters/AbstractFileParameterDefinition.java
Labels: bug

#13 Ability to use build step on Base64 file parameter values
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/file_parameters/Base64FileParameterValue.java
Labels: enhancement

#14 Pad short parameter names before using File.createTempFile
  src/main/java/io/jenkins/plugins/file_parameters/AbstractFileParameterValue.java
  src/test/java/io/jenkins/plugins/file_parameters/FileParameterWrapperTest.java
Labels: bug

#19 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: chore
